@baseUrl = http://localhost:8081/api/v1/countries
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkNGRkb2lhOGhtcm4ybzRqZGppMCIsImp0aSI6ImQ0ZXBnNmE1bWpqNHQ5MXZjNWNnIiwic2lkIjoiZDRlcGc2YThobXJsMDdramRqbGciLCJleHAiOjE3NjM1NDgwNjEsImlhdCI6MTc2MzU0NzE2MX0.NmxKfcKIataRX4HLF6NlKP6VAt-JiPkqPQmx6b_pk7g

###

GET {{baseUrl}}
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/currencies
Authorization: Bearer {{accessToken}}

###
