
@baseUrl = http://localhost:8081/api/v1/currencies
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkNGRkb2lhOGhtcm4ybzRqZGppMCIsImp0aSI6ImQ0ZWxrcWk1bWpqYzRmdXAxZzFnIiwic2lkIjoiZDRlbGtxaThobXJzNW9zamRqamciLCJleHAiOjE3NjM1MzIyNzAsImlhdCI6MTc2MzUzMTM3MH0.0rgB4oRY087PT8G4Q8a39fn_8sNVJyVX8_Frdbq6hKQ

###

GET {{baseUrl}}
Authorization: Bearer {{accessToken}}

###

GET {{baseUrl}}/countries
Authorization: Bearer {{accessToken}}

###
