// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: auth_queries.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authBlockUserByID = `-- name: AuthBlockUserByID :one
UPDATE users
   SET is_blocked = true, blocked_at = timezone('utc', now())
 WHERE id = $1 RETURNING id, username, is_blocked, blocked_at
`

type AuthBlockUserByIDRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	IsBlocked bool             `json:"is_blocked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
}

// AuthBlockUserByID
//
//	UPDATE users
//	   SET is_blocked = true, blocked_at = timezone('utc', now())
//	 WHERE id = $1 RETURNING id, username, is_blocked, blocked_at
func (q *Queries) AuthBlockUserByID(ctx context.Context, id string) (*AuthBlockUserByIDRow, error) {
	row := q.db.QueryRow(ctx, authBlockUserByID, id)
	var i AuthBlockUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsBlocked,
		&i.BlockedAt,
	)
	return &i, err
}

const authCreateUser = `-- name: AuthCreateUser :one
INSERT INTO users (username, password, is_checked)
VALUES ($1, $2, $3)
RETURNING id, username, password, is_blocked, is_checked, blocked_at, checked_at, visited_at, created_at, updated_at
`

type AuthCreateUserParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	IsChecked bool   `json:"is_checked"`
}

type AuthCreateUserRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	IsBlocked bool             `json:"is_blocked"`
	IsChecked bool             `json:"is_checked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
	CheckedAt pgtype.Timestamp `json:"checked_at"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// AuthCreateUser
//
//	INSERT INTO users (username, password, is_checked)
//	VALUES ($1, $2, $3)
//	RETURNING id, username, password, is_blocked, is_checked, blocked_at, checked_at, visited_at, created_at, updated_at
func (q *Queries) AuthCreateUser(ctx context.Context, arg *AuthCreateUserParams) (*AuthCreateUserRow, error) {
	row := q.db.QueryRow(ctx, authCreateUser, arg.Username, arg.Password, arg.IsChecked)
	var i AuthCreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.IsChecked,
		&i.BlockedAt,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const authGetUserGrants = `-- name: AuthGetUserGrants :many
SELECT g.code
  FROM user_roles ur
  JOIN role_grants rg ON rg.role_id = ur.role_id
  JOIN grants g       ON g.id = rg.grant_id
 WHERE ur.user_id = $1
`

// AuthGetUserGrants
//
//	SELECT g.code
//	  FROM user_roles ur
//	  JOIN role_grants rg ON rg.role_id = ur.role_id
//	  JOIN grants g       ON g.id = rg.grant_id
//	 WHERE ur.user_id = $1
func (q *Queries) AuthGetUserGrants(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, authGetUserGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const authSelectUserByID = `-- name: AuthSelectUserByID :one
SELECT id, username, password, is_blocked, is_checked, blocked_at, checked_at, visited_at, created_at, updated_at
  FROM users
 WHERE id = $1
`

type AuthSelectUserByIDRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	IsBlocked bool             `json:"is_blocked"`
	IsChecked bool             `json:"is_checked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
	CheckedAt pgtype.Timestamp `json:"checked_at"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// AuthSelectUserByID
//
//	SELECT id, username, password, is_blocked, is_checked, blocked_at, checked_at, visited_at, created_at, updated_at
//	  FROM users
//	 WHERE id = $1
func (q *Queries) AuthSelectUserByID(ctx context.Context, id string) (*AuthSelectUserByIDRow, error) {
	row := q.db.QueryRow(ctx, authSelectUserByID, id)
	var i AuthSelectUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.IsChecked,
		&i.BlockedAt,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const authSelectUserCredentials = `-- name: AuthSelectUserCredentials :one
SELECT id, username, password, is_blocked, is_checked, blocked_at, checked_at
  FROM users
 WHERE username = $1
`

type AuthSelectUserCredentialsRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	Password  string           `json:"password"`
	IsBlocked bool             `json:"is_blocked"`
	IsChecked bool             `json:"is_checked"`
	BlockedAt pgtype.Timestamp `json:"blocked_at"`
	CheckedAt pgtype.Timestamp `json:"checked_at"`
}

// AuthSelectUserCredentials
//
//	SELECT id, username, password, is_blocked, is_checked, blocked_at, checked_at
//	  FROM users
//	 WHERE username = $1
func (q *Queries) AuthSelectUserCredentials(ctx context.Context, username string) (*AuthSelectUserCredentialsRow, error) {
	row := q.db.QueryRow(ctx, authSelectUserCredentials, username)
	var i AuthSelectUserCredentialsRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.IsChecked,
		&i.BlockedAt,
		&i.CheckedAt,
	)
	return &i, err
}

const authUpdateVisitedAt = `-- name: AuthUpdateVisitedAt :one
UPDATE users
   SET visited_at = timezone('utc', now())
 WHERE id = $1 RETURNING id, username, visited_at, created_at, updated_at
`

type AuthUpdateVisitedAtRow struct {
	ID        string           `json:"id"`
	Username  string           `json:"username"`
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

// AuthUpdateVisitedAt
//
//	UPDATE users
//	   SET visited_at = timezone('utc', now())
//	 WHERE id = $1 RETURNING id, username, visited_at, created_at, updated_at
func (q *Queries) AuthUpdateVisitedAt(ctx context.Context, id string) (*AuthUpdateVisitedAtRow, error) {
	row := q.db.QueryRow(ctx, authUpdateVisitedAt, id)
	var i AuthUpdateVisitedAtRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
