// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contact.sql

package dbs

import (
	"context"
)

const createContact = `-- name: CreateContact :one

INSERT INTO contact (user_id, class, content)
VALUES ($1,$2,$3)
RETURNING id, user_id, class, content, created_at, updated_at
`

type CreateContactParams struct {
	UserID  string `json:"user_id"`
	Class   string `json:"class"`
	Content string `json:"content"`
}

// Contact
// Create
//
//	INSERT INTO contact (user_id, class, content)
//	VALUES ($1,$2,$3)
//	RETURNING id, user_id, class, content, created_at, updated_at
func (q *Queries) CreateContact(ctx context.Context, arg *CreateContactParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, createContact, arg.UserID, arg.Class, arg.Content)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteContactByID = `-- name: DeleteContactByID :one
DELETE FROM contact WHERE id=$1
RETURNING id, user_id, class, content, created_at, updated_at
`

// Delete
//
//	DELETE FROM contact WHERE id=$1
//	RETURNING id, user_id, class, content, created_at, updated_at
func (q *Queries) DeleteContactByID(ctx context.Context, id string) (*Contact, error) {
	row := q.db.QueryRow(ctx, deleteContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, user_id, class, content, created_at, updated_at FROM contact WHERE id = $1
`

// Get by ID
//
//	SELECT id, user_id, class, content, created_at, updated_at FROM contact WHERE id = $1
func (q *Queries) GetContactByID(ctx context.Context, id string) (*Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listContactsByUserID = `-- name: ListContactsByUserID :many
SELECT id, user_id, class, content, created_at, updated_at FROM contact WHERE user_id = $1 ORDER BY created_at DESC
`

// List by UserID
//
//	SELECT id, user_id, class, content, created_at, updated_at FROM contact WHERE user_id = $1 ORDER BY created_at DESC
func (q *Queries) ListContactsByUserID(ctx context.Context, userID string) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Class,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactByID = `-- name: UpdateContactByID :one
UPDATE contact
SET class=$2, content=$3
WHERE id=$1
RETURNING id, user_id, class, content, created_at, updated_at
`

type UpdateContactByIDParams struct {
	ID      string `json:"id"`
	Class   string `json:"class"`
	Content string `json:"content"`
}

// Update
//
//	UPDATE contact
//	SET class=$2, content=$3
//	WHERE id=$1
//	RETURNING id, user_id, class, content, created_at, updated_at
func (q *Queries) UpdateContactByID(ctx context.Context, arg *UpdateContactByIDParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, updateContactByID, arg.ID, arg.Class, arg.Content)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
