// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: contact.sql

package dbs

import (
	"context"
)

const createContact = `-- name: CreateContact :one
insert into contact(user_id, class, content)
values($1, $2, $3)
returning id, user_id, class, content, created_at, updated_at
`

type CreateContactParams struct {
	UserID  string `json:"user_id"`
	Class   string `json:"class"`
	Content string `json:"content"`
}

// CreateContact
//
//	insert into contact(user_id, class, content)
//	values($1, $2, $3)
//	returning id, user_id, class, content, created_at, updated_at
func (q *Queries) CreateContact(ctx context.Context, arg *CreateContactParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, createContact, arg.UserID, arg.Class, arg.Content)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteContactByID = `-- name: DeleteContactByID :one
delete from contact where id = $1 returning id
`

// DeleteContactByID
//
//	delete from contact where id = $1 returning id
func (q *Queries) DeleteContactByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteContactByID, id)
	err := row.Scan(&id)
	return id, err
}

const getContactByID = `-- name: GetContactByID :one
select id, user_id, class, content, created_at, updated_at
from contact
where id = $1
`

// GetContactByID
//
//	select id, user_id, class, content, created_at, updated_at
//	from contact
//	where id = $1
func (q *Queries) GetContactByID(ctx context.Context, id string) (*Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listContactsByUserID = `-- name: ListContactsByUserID :many
select id, user_id, class, content, created_at, updated_at
from contact
where user_id = $1
order by class, content
`

// ListContactsByUserID
//
//	select id, user_id, class, content, created_at, updated_at
//	from contact
//	where user_id = $1
//	order by class, content
func (q *Queries) ListContactsByUserID(ctx context.Context, userID string) ([]*Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Class,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
update contact
set class = $1,
    content = $2
where id = $3
returning id, user_id, class, content, created_at, updated_at
`

type UpdateContactParams struct {
	Class   string `json:"class"`
	Content string `json:"content"`
	ID      string `json:"id"`
}

// UpdateContact
//
//	update contact
//	set class = $1,
//	    content = $2
//	where id = $3
//	returning id, user_id, class, content, created_at, updated_at
func (q *Queries) UpdateContact(ctx context.Context, arg *UpdateContactParams) (*Contact, error) {
	row := q.db.QueryRow(ctx, updateContact, arg.Class, arg.Content, arg.ID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Class,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
