// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: country.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCountries = `-- name: CountCountries :one
SELECT count(*) FROM country
`

// CountCountries
//
//	SELECT count(*) FROM country
func (q *Queries) CountCountries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCountries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCountry = `-- name: CreateCountry :one
INSERT INTO country (
	name, iso2, iso3, num_code
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, name, iso2, iso3, num_code, created_at, updated_at
`

type CreateCountryParams struct {
	Name    string `json:"name"`
	Iso2    string `json:"iso2"`
	Iso3    string `json:"iso3"`
	NumCode int16  `json:"num_code"`
}

// CreateCountry
//
//	INSERT INTO country (
//		name, iso2, iso3, num_code
//	) VALUES (
//		$1, $2, $3, $4
//	)
//	RETURNING id, name, iso2, iso3, num_code, created_at, updated_at
func (q *Queries) CreateCountry(ctx context.Context, arg *CreateCountryParams) (*Country, error) {
	row := q.db.QueryRow(ctx, createCountry,
		arg.Name,
		arg.Iso2,
		arg.Iso3,
		arg.NumCode,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.NumCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCountryByID = `-- name: DeleteCountryByID :one
DELETE FROM country c WHERE c.id = $1 RETURNING id
`

// DeleteCountryByID
//
//	DELETE FROM country c WHERE c.id = $1 RETURNING id
func (q *Queries) DeleteCountryByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteCountryByID, id)
	err := row.Scan(&id)
	return id, err
}

const getCountryByID = `-- name: GetCountryByID :one
SELECT id, name, iso2, iso3, num_code, created_at, updated_at FROM country c WHERE c.id = $1
`

// GetCountryByID
//
//	SELECT id, name, iso2, iso3, num_code, created_at, updated_at FROM country c WHERE c.id = $1
func (q *Queries) GetCountryByID(ctx context.Context, id string) (*Country, error) {
	row := q.db.QueryRow(ctx, getCountryByID, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.NumCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCountries = `-- name: ListCountries :many
SELECT id, name, iso2, iso3, num_code, created_at, updated_at
  FROM country c
 ORDER BY
    CASE WHEN $1 = 'asc' THEN name END ASC,
    CASE WHEN $1 = 'desc' THEN name END DESC
 LIMIT $3 OFFSET $2
`

type ListCountriesParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

// ListCountries
//
//	SELECT id, name, iso2, iso3, num_code, created_at, updated_at
//	  FROM country c
//	 ORDER BY
//	    CASE WHEN $1 = 'asc' THEN name END ASC,
//	    CASE WHEN $1 = 'desc' THEN name END DESC
//	 LIMIT $3 OFFSET $2
func (q *Queries) ListCountries(ctx context.Context, arg *ListCountriesParams) ([]*Country, error) {
	rows, err := q.db.Query(ctx, listCountries, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso2,
			&i.Iso3,
			&i.NumCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountriesWithCurrencies = `-- name: ListCountriesWithCurrencies :many
SELECT cn.id,
       cn.name,
       cn.iso2,
       cn.iso3,
       cn.num_code,
       cn.created_at,
       cn.updated_at,
  COALESCE(
    JSON_AGG(
      JSONB_BUILD_OBJECT(
        'id',         cr.id,
        'name',       cr.name,
        'code',       cr.code,
        'num_code',   cr.num_code,
        'symbol',     cr.symbol,
        'created_at', cr.created_at,
        'updated_at', cr.updated_at
      )
    ) FILTER (WHERE cr.id IS NOT NULL), '[]'
  ) AS currencies
  FROM country cn
  LEFT JOIN country_currency cc ON cn.id = cc.country_id
  LEFT JOIN currency cr ON cc.currency_id = cr.id
 GROUP BY cn.id, cn.name
 ORDER BY
    CASE WHEN $1 = 'asc' THEN cn.name END ASC,
    CASE WHEN $1 = 'desc' THEN cn.name END DESC
 LIMIT  $3 OFFSET $2
`

type ListCountriesWithCurrenciesParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

type ListCountriesWithCurrenciesRow struct {
	ID         string           `json:"id"`
	Name       string           `json:"name"`
	Iso2       string           `json:"iso2"`
	Iso3       string           `json:"iso3"`
	NumCode    int16            `json:"num_code"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
	Currencies interface{}      `json:"currencies"`
}

// ListCountriesWithCurrencies
//
//	SELECT cn.id,
//	       cn.name,
//	       cn.iso2,
//	       cn.iso3,
//	       cn.num_code,
//	       cn.created_at,
//	       cn.updated_at,
//	  COALESCE(
//	    JSON_AGG(
//	      JSONB_BUILD_OBJECT(
//	        'id',         cr.id,
//	        'name',       cr.name,
//	        'code',       cr.code,
//	        'num_code',   cr.num_code,
//	        'symbol',     cr.symbol,
//	        'created_at', cr.created_at,
//	        'updated_at', cr.updated_at
//	      )
//	    ) FILTER (WHERE cr.id IS NOT NULL), '[]'
//	  ) AS currencies
//	  FROM country cn
//	  LEFT JOIN country_currency cc ON cn.id = cc.country_id
//	  LEFT JOIN currency cr ON cc.currency_id = cr.id
//	 GROUP BY cn.id, cn.name
//	 ORDER BY
//	    CASE WHEN $1 = 'asc' THEN cn.name END ASC,
//	    CASE WHEN $1 = 'desc' THEN cn.name END DESC
//	 LIMIT  $3 OFFSET $2
func (q *Queries) ListCountriesWithCurrencies(ctx context.Context, arg *ListCountriesWithCurrenciesParams) ([]*ListCountriesWithCurrenciesRow, error) {
	rows, err := q.db.Query(ctx, listCountriesWithCurrencies, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCountriesWithCurrenciesRow
	for rows.Next() {
		var i ListCountriesWithCurrenciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Iso2,
			&i.Iso3,
			&i.NumCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Currencies,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCountryByID = `-- name: UpdateCountryByID :one
UPDATE country
   SET name = $1,
       iso2 = $2,
       iso3 = $3,
       num_code = $4
 WHERE id = $5
 RETURNING id, name, iso2, iso3, num_code, created_at, updated_at
`

type UpdateCountryByIDParams struct {
	Name    string `json:"name"`
	Iso2    string `json:"iso2"`
	Iso3    string `json:"iso3"`
	NumCode int16  `json:"num_code"`
	ID      string `json:"id"`
}

// UpdateCountryByID
//
//	UPDATE country
//	   SET name = $1,
//	       iso2 = $2,
//	       iso3 = $3,
//	       num_code = $4
//	 WHERE id = $5
//	 RETURNING id, name, iso2, iso3, num_code, created_at, updated_at
func (q *Queries) UpdateCountryByID(ctx context.Context, arg *UpdateCountryByIDParams) (*Country, error) {
	row := q.db.QueryRow(ctx, updateCountryByID,
		arg.Name,
		arg.Iso2,
		arg.Iso3,
		arg.NumCode,
		arg.ID,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Iso2,
		&i.Iso3,
		&i.NumCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
