// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: currency.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCurrencies = `-- name: CountCurrencies :one
SELECT count(*) FROM currency
`

// CountCurrencies
//
//	SELECT count(*) FROM currency
func (q *Queries) CountCurrencies(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCurrencies)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currency (
	name, code, num_code, symbol
) VALUES (
	$1, $2, $3, $4
)
RETURNING id, name, code, num_code, symbol, created_at, updated_at
`

type CreateCurrencyParams struct {
	Name    string `json:"name"`
	Code    string `json:"code"`
	NumCode int16  `json:"num_code"`
	Symbol  string `json:"symbol"`
}

// CreateCurrency
//
//	INSERT INTO currency (
//		name, code, num_code, symbol
//	) VALUES (
//		$1, $2, $3, $4
//	)
//	RETURNING id, name, code, num_code, symbol, created_at, updated_at
func (q *Queries) CreateCurrency(ctx context.Context, arg *CreateCurrencyParams) (*Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency,
		arg.Name,
		arg.Code,
		arg.NumCode,
		arg.Symbol,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.NumCode,
		&i.Symbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCurrencyByID = `-- name: DeleteCurrencyByID :one
DELETE FROM currency c WHERE c.id = $1 RETURNING id
`

// DeleteCurrencyByID
//
//	DELETE FROM currency c WHERE c.id = $1 RETURNING id
func (q *Queries) DeleteCurrencyByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteCurrencyByID, id)
	err := row.Scan(&id)
	return id, err
}

const getCurrencyByID = `-- name: GetCurrencyByID :one
SELECT id, name, code, num_code, symbol, created_at, updated_at FROM currency c WHERE c.id = $1
`

// GetCurrencyByID
//
//	SELECT id, name, code, num_code, symbol, created_at, updated_at FROM currency c WHERE c.id = $1
func (q *Queries) GetCurrencyByID(ctx context.Context, id string) (*Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByID, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.NumCode,
		&i.Symbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, name, code, num_code, symbol, created_at, updated_at
  FROM currency c
 ORDER BY
  CASE WHEN $1 = 'asc' THEN name END ASC,
  CASE WHEN $1 = 'desc' THEN name END DESC,
    name ASC
 LIMIT $3 OFFSET $2
`

type ListCurrenciesParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

// ListCurrencies
//
//	SELECT id, name, code, num_code, symbol, created_at, updated_at
//	  FROM currency c
//	 ORDER BY
//	  CASE WHEN $1 = 'asc' THEN name END ASC,
//	  CASE WHEN $1 = 'desc' THEN name END DESC,
//	    name ASC
//	 LIMIT $3 OFFSET $2
func (q *Queries) ListCurrencies(ctx context.Context, arg *ListCurrenciesParams) ([]*Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Currency
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.NumCode,
			&i.Symbol,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrenciesWithCountries = `-- name: ListCurrenciesWithCountries :many
SELECT cr.id,
       cr.name,
       cr.code,
       cr.num_code,
       cr.symbol,
       cr.created_at,
       cr.updated_at,
  COALESCE(
    JSON_AGG(
      JSONB_BUILD_OBJECT(
        'id',         cn.id,
        'name',       cn.name,
        'iso2',       cn.iso2,
        'iso3',       cn.iso3,
        'num_code',   cn.num_code,
        'created_at', cn.created_at,
        'updated_at', cn.updated_at
      )
    ) FILTER (WHERE cn.id IS NOT NULL), '[]'
  ) AS countries
  FROM currency cr
  LEFT JOIN country_currency cc ON cr.id = cc.currency_id
  LEFT JOIN country cn ON cc.country_id = cn.id
 GROUP BY cr.id, cr.name
 ORDER BY
  CASE WHEN $1 = 'asc' THEN cr.name END ASC,
  CASE WHEN $1 = 'desc' THEN cr.name END DESC,
    cr.name ASC
 LIMIT $3 OFFSET $2
`

type ListCurrenciesWithCountriesParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

type ListCurrenciesWithCountriesRow struct {
	ID        string           `json:"id"`
	Name      string           `json:"name"`
	Code      string           `json:"code"`
	NumCode   int16            `json:"num_code"`
	Symbol    string           `json:"symbol"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Countries interface{}      `json:"countries"`
}

// ListCurrenciesWithCountries
//
//	SELECT cr.id,
//	       cr.name,
//	       cr.code,
//	       cr.num_code,
//	       cr.symbol,
//	       cr.created_at,
//	       cr.updated_at,
//	  COALESCE(
//	    JSON_AGG(
//	      JSONB_BUILD_OBJECT(
//	        'id',         cn.id,
//	        'name',       cn.name,
//	        'iso2',       cn.iso2,
//	        'iso3',       cn.iso3,
//	        'num_code',   cn.num_code,
//	        'created_at', cn.created_at,
//	        'updated_at', cn.updated_at
//	      )
//	    ) FILTER (WHERE cn.id IS NOT NULL), '[]'
//	  ) AS countries
//	  FROM currency cr
//	  LEFT JOIN country_currency cc ON cr.id = cc.currency_id
//	  LEFT JOIN country cn ON cc.country_id = cn.id
//	 GROUP BY cr.id, cr.name
//	 ORDER BY
//	  CASE WHEN $1 = 'asc' THEN cr.name END ASC,
//	  CASE WHEN $1 = 'desc' THEN cr.name END DESC,
//	    cr.name ASC
//	 LIMIT $3 OFFSET $2
func (q *Queries) ListCurrenciesWithCountries(ctx context.Context, arg *ListCurrenciesWithCountriesParams) ([]*ListCurrenciesWithCountriesRow, error) {
	rows, err := q.db.Query(ctx, listCurrenciesWithCountries, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListCurrenciesWithCountriesRow
	for rows.Next() {
		var i ListCurrenciesWithCountriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.NumCode,
			&i.Symbol,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Countries,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCurrencyByID = `-- name: UpdateCurrencyByID :one
UPDATE currency
   SET name = $1, code = $2, num_code = $3, symbol = $4
 WHERE id = $5
       RETURNING id, name, code, num_code, symbol, created_at, updated_at
`

type UpdateCurrencyByIDParams struct {
	Name    string `json:"name"`
	Code    string `json:"code"`
	NumCode int16  `json:"num_code"`
	Symbol  string `json:"symbol"`
	ID      string `json:"id"`
}

// UpdateCurrencyByID
//
//	UPDATE currency
//	   SET name = $1, code = $2, num_code = $3, symbol = $4
//	 WHERE id = $5
//	       RETURNING id, name, code, num_code, symbol, created_at, updated_at
func (q *Queries) UpdateCurrencyByID(ctx context.Context, arg *UpdateCurrencyByIDParams) (*Currency, error) {
	row := q.db.QueryRow(ctx, updateCurrencyByID,
		arg.Name,
		arg.Code,
		arg.NumCode,
		arg.Symbol,
		arg.ID,
	)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.NumCode,
		&i.Symbol,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
