// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: grants_queries.sql

package dbs

import (
	"context"
)

const countGrants = `-- name: CountGrants :one
SELECT COUNT(*) FROM grants
`

// CountGrants
//
//	SELECT COUNT(*) FROM grants
func (q *Queries) CountGrants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGrants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO grants (code, description) VALUES ($1, $2)
RETURNING id, pid, code, description, created_at, updated_at
`

type CreateGrantParams struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

// CreateGrant
//
//	INSERT INTO grants (code, description) VALUES ($1, $2)
//	RETURNING id, pid, code, description, created_at, updated_at
func (q *Queries) CreateGrant(ctx context.Context, arg *CreateGrantParams) (*Grant, error) {
	row := q.db.QueryRow(ctx, createGrant, arg.Code, arg.Description)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteGrantByID = `-- name: DeleteGrantByID :one
DELETE FROM grants WHERE pid = $1 RETURNING id, pid, code, description, created_at, updated_at
`

// DeleteGrantByID
//
//	DELETE FROM grants WHERE pid = $1 RETURNING id, pid, code, description, created_at, updated_at
func (q *Queries) DeleteGrantByID(ctx context.Context, pid string) (*Grant, error) {
	row := q.db.QueryRow(ctx, deleteGrantByID, pid)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getGrantByCode = `-- name: GetGrantByCode :one
SELECT id, pid, code, description, created_at, updated_at FROM grants WHERE code = $1
`

// GetGrantByCode
//
//	SELECT id, pid, code, description, created_at, updated_at FROM grants WHERE code = $1
func (q *Queries) GetGrantByCode(ctx context.Context, code string) (*Grant, error) {
	row := q.db.QueryRow(ctx, getGrantByCode, code)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getGrantByID = `-- name: GetGrantByID :one
SELECT id, pid, code, description, created_at, updated_at FROM grants WHERE pid = $1
`

// GetGrantByID
//
//	SELECT id, pid, code, description, created_at, updated_at FROM grants WHERE pid = $1
func (q *Queries) GetGrantByID(ctx context.Context, pid string) (*Grant, error) {
	row := q.db.QueryRow(ctx, getGrantByID, pid)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listGrants = `-- name: ListGrants :many
SELECT id, pid, code, description, created_at, updated_at
  FROM grants
 ORDER BY
    CASE WHEN $1 = 'asc' THEN code END ASC,
    CASE WHEN $1 = 'desc' THEN code END DESC,
      code ASC
 LIMIT $3 OFFSET $2
`

type ListGrantsParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

// ListGrants
//
//	SELECT id, pid, code, description, created_at, updated_at
//	  FROM grants
//	 ORDER BY
//	    CASE WHEN $1 = 'asc' THEN code END ASC,
//	    CASE WHEN $1 = 'desc' THEN code END DESC,
//	      code ASC
//	 LIMIT $3 OFFSET $2
func (q *Queries) ListGrants(ctx context.Context, arg *ListGrantsParams) ([]*Grant, error) {
	rows, err := q.db.Query(ctx, listGrants, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Grant
	for rows.Next() {
		var i Grant
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGrantByID = `-- name: UpdateGrantByID :one
UPDATE grants
   SET code = $1, description = $2
 WHERE pid = $3 RETURNING id, pid, code, description, created_at, updated_at
`

type UpdateGrantByIDParams struct {
	Code        string `json:"code"`
	Description string `json:"description"`
	Pid         string `json:"pid"`
}

// UpdateGrantByID
//
//	UPDATE grants
//	   SET code = $1, description = $2
//	 WHERE pid = $3 RETURNING id, pid, code, description, created_at, updated_at
func (q *Queries) UpdateGrantByID(ctx context.Context, arg *UpdateGrantByIDParams) (*Grant, error) {
	row := q.db.QueryRow(ctx, updateGrantByID, arg.Code, arg.Description, arg.Pid)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
