// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: profile.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfileByUserID = `-- name: GetProfileByUserID :one
select id, user_id, firstname, lastname, gender, birthday, avatar_url, enable_2fa, secret_2fa, created_at, updated_at
from profile
where user_id = $1
`

// GetProfileByUserID
//
//	select id, user_id, firstname, lastname, gender, birthday, avatar_url, enable_2fa, secret_2fa, created_at, updated_at
//	from profile
//	where user_id = $1
func (q *Queries) GetProfileByUserID(ctx context.Context, userID string) (*Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByUserID, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Firstname,
		&i.Lastname,
		&i.Gender,
		&i.Birthday,
		&i.AvatarUrl,
		&i.Enable2fa,
		&i.Secret2fa,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateProfileByUserID = `-- name: UpdateProfileByUserID :one
update profile
set firstname = $1,
    lastname = $2,
    gender = $3,
    birthday = $4,
    avatar_url = $5,
    enable_2fa = $6,
    secret_2fa = $7
where user_id = $8
returning id, user_id, firstname, lastname, gender, birthday, avatar_url, enable_2fa, secret_2fa, created_at, updated_at
`

type UpdateProfileByUserIDParams struct {
	Firstname string      `json:"firstname"`
	Lastname  string      `json:"lastname"`
	Gender    string      `json:"gender"`
	Birthday  pgtype.Date `json:"birthday"`
	AvatarUrl string      `json:"avatar_url"`
	Enable2fa bool        `json:"enable_2fa"`
	Secret2fa pgtype.Text `json:"secret_2fa"`
	UserID    string      `json:"user_id"`
}

// UpdateProfileByUserID
//
//	update profile
//	set firstname = $1,
//	    lastname = $2,
//	    gender = $3,
//	    birthday = $4,
//	    avatar_url = $5,
//	    enable_2fa = $6,
//	    secret_2fa = $7
//	where user_id = $8
//	returning id, user_id, firstname, lastname, gender, birthday, avatar_url, enable_2fa, secret_2fa, created_at, updated_at
func (q *Queries) UpdateProfileByUserID(ctx context.Context, arg *UpdateProfileByUserIDParams) (*Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileByUserID,
		arg.Firstname,
		arg.Lastname,
		arg.Gender,
		arg.Birthday,
		arg.AvatarUrl,
		arg.Enable2fa,
		arg.Secret2fa,
		arg.UserID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Firstname,
		&i.Lastname,
		&i.Gender,
		&i.Birthday,
		&i.AvatarUrl,
		&i.Enable2fa,
		&i.Secret2fa,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
