// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles_queries.sql

package dbs

import (
	"context"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM roles
`

// CountRoles
//
//	SELECT COUNT(*) FROM roles
func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description) VALUES ($1, $2)
RETURNING id, pid, name, description, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// CreateRole
//
//	INSERT INTO roles (name, description) VALUES ($1, $2)
//	RETURNING id, pid, name, description, created_at, updated_at
func (q *Queries) CreateRole(ctx context.Context, arg *CreateRoleParams) (*Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRoleByID = `-- name: DeleteRoleByID :one
DELETE FROM roles WHERE pid = $1 RETURNING id, pid, name, description, created_at, updated_at
`

// DeleteRoleByID
//
//	DELETE FROM roles WHERE pid = $1 RETURNING id, pid, name, description, created_at, updated_at
func (q *Queries) DeleteRoleByID(ctx context.Context, pid string) (*Role, error) {
	row := q.db.QueryRow(ctx, deleteRoleByID, pid)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, pid, name, description, created_at, updated_at FROM roles WHERE pid = $1
`

// GetRoleByID
//
//	SELECT id, pid, name, description, created_at, updated_at FROM roles WHERE pid = $1
func (q *Queries) GetRoleByID(ctx context.Context, pid string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, pid)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, pid, name, description, created_at, updated_at FROM roles WHERE name = $1
`

// GetRoleByName
//
//	SELECT id, pid, name, description, created_at, updated_at FROM roles WHERE name = $1
func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, pid, name, description, created_at, updated_at
  FROM roles
 ORDER BY
    CASE WHEN $1 = 'asc' THEN name END ASC,
    CASE WHEN $1 = 'desc' THEN name END DESC,
      name ASC
 LIMIT $3 OFFSET $2
`

type ListRolesParams struct {
	SqlOrder  interface{} `json:"sql_order"`
	SqlOffset int32       `json:"sql_offset"`
	SqlLimit  int32       `json:"sql_limit"`
}

// ListRoles
//
//	SELECT id, pid, name, description, created_at, updated_at
//	  FROM roles
//	 ORDER BY
//	    CASE WHEN $1 = 'asc' THEN name END ASC,
//	    CASE WHEN $1 = 'desc' THEN name END DESC,
//	      name ASC
//	 LIMIT $3 OFFSET $2
func (q *Queries) ListRoles(ctx context.Context, arg *ListRolesParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleByID = `-- name: UpdateRoleByID :one
UPDATE roles
   SET name = $1, description = $2
 WHERE pid = $3 RETURNING id, pid, name, description, created_at, updated_at
`

type UpdateRoleByIDParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Pid         string `json:"pid"`
}

// UpdateRoleByID
//
//	UPDATE roles
//	   SET name = $1, description = $2
//	 WHERE pid = $3 RETURNING id, pid, name, description, created_at, updated_at
func (q *Queries) UpdateRoleByID(ctx context.Context, arg *UpdateRoleByIDParams) (*Role, error) {
	row := q.db.QueryRow(ctx, updateRoleByID, arg.Name, arg.Description, arg.Pid)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
