// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.sql

package dbs

import (
	"context"
)

const countRoles = `-- name: CountRoles :one
select count(*) from roles
`

// CountRoles
//
//	select count(*) from roles
func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
insert into roles(name) values($1) returning id, name, created_at, updated_at
`

// CreateRole
//
//	insert into roles(name) values($1) returning id, name, created_at, updated_at
func (q *Queries) CreateRole(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, createRole, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRoleByID = `-- name: DeleteRoleByID :one
delete from roles where id = $1 returning id
`

// DeleteRoleByID
//
//	delete from roles where id = $1 returning id
func (q *Queries) DeleteRoleByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteRoleByID, id)
	err := row.Scan(&id)
	return id, err
}

const getRoleByID = `-- name: GetRoleByID :one
select id, name, created_at, updated_at from roles r where r.id = $1
`

// GetRoleByID
//
//	select id, name, created_at, updated_at from roles r where r.id = $1
func (q *Queries) GetRoleByID(ctx context.Context, id string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByName = `-- name: GetRoleByName :one
select id, name, created_at, updated_at from roles r where r.name = $1
`

// GetRoleByName
//
//	select id, name, created_at, updated_at from roles r where r.name = $1
func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRoles = `-- name: ListRoles :many
select id, name, created_at, updated_at
  from roles r
 order by $1::text
 limit $3 offset $2
`

type ListRolesParams struct {
	SqlOrder  string `json:"sql_order"`
	SqlOffset int32  `json:"sql_offset"`
	SqlLimit  int32  `json:"sql_limit"`
}

// ListRoles
//
//	select id, name, created_at, updated_at
//	  from roles r
//	 order by $1::text
//	 limit $3 offset $2
func (q *Queries) ListRoles(ctx context.Context, arg *ListRolesParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleByID = `-- name: UpdateRoleByID :one
update roles
   set name = $1 where id = $2 returning id, name, created_at, updated_at
`

type UpdateRoleByIDParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

// UpdateRoleByID
//
//	update roles
//	   set name = $1 where id = $2 returning id, name, created_at, updated_at
func (q *Queries) UpdateRoleByID(ctx context.Context, arg *UpdateRoleByIDParams) (*Role, error) {
	row := q.db.QueryRow(ctx, updateRoleByID, arg.Name, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
