// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.sql

package dbs

import (
	"context"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM roles
`

// Count
//
//	SELECT COUNT(*) FROM roles
func (q *Queries) CountRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO roles (name) VALUES ($1)
RETURNING id, name, created_at, updated_at
`

// Roles
// Create
//
//	INSERT INTO roles (name) VALUES ($1)
//	RETURNING id, name, created_at, updated_at
func (q *Queries) CreateRole(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, createRole, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteRoleByID = `-- name: DeleteRoleByID :one
DELETE FROM roles WHERE id = $1
RETURNING id, name, created_at, updated_at
`

// Delete
//
//	DELETE FROM roles WHERE id = $1
//	RETURNING id, name, created_at, updated_at
func (q *Queries) DeleteRoleByID(ctx context.Context, id string) (*Role, error) {
	row := q.db.QueryRow(ctx, deleteRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, created_at, updated_at FROM roles WHERE id = $1
`

// Get by ID
//
//	SELECT id, name, created_at, updated_at FROM roles WHERE id = $1
func (q *Queries) GetRoleByID(ctx context.Context, id string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, created_at, updated_at FROM roles WHERE name = $1
`

// Get by name
//
//	SELECT id, name, created_at, updated_at FROM roles WHERE name = $1
func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, created_at, updated_at
FROM roles
ORDER BY
    CASE WHEN $1 = 'asc' THEN name END ASC,
    CASE WHEN $1 = 'desc' THEN name END DESC
LIMIT $3 OFFSET $2
`

type ListRolesParams struct {
	Sqlorder  interface{} `json:"sqlorder"`
	Sqloffset int32       `json:"sqloffset"`
	Sqllimit  int32       `json:"sqllimit"`
}

// List with pagination
//
//	SELECT id, name, created_at, updated_at
//	FROM roles
//	ORDER BY
//	    CASE WHEN $1 = 'asc' THEN name END ASC,
//	    CASE WHEN $1 = 'desc' THEN name END DESC
//	LIMIT $3 OFFSET $2
func (q *Queries) ListRoles(ctx context.Context, arg *ListRolesParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Sqlorder, arg.Sqloffset, arg.Sqllimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRoleByID = `-- name: UpdateRoleByID :one
UPDATE roles
SET name = $2
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateRoleByIDParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// Update
//
//	UPDATE roles
//	SET name = $2
//	WHERE id = $1
//	RETURNING id, name, created_at, updated_at
func (q *Queries) UpdateRoleByID(ctx context.Context, arg *UpdateRoleByIDParams) (*Role, error) {
	row := q.db.QueryRow(ctx, updateRoleByID, arg.ID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
