// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one

INSERT INTO session (
  user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, ip_address, user_agent
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

type CreateSessionParams struct {
	UserID       string           `json:"user_id"`
	AccessToken  string           `json:"access_token"`
	RefreshToken string           `json:"refresh_token"`
	AccessExp    pgtype.Timestamp `json:"access_exp"`
	RefreshExp   pgtype.Timestamp `json:"refresh_exp"`
	AccessJti    string           `json:"access_jti"`
	RefreshJti   string           `json:"refresh_jti"`
	IpAddress    string           `json:"ip_address"`
	UserAgent    string           `json:"user_agent"`
}

// Session
//
//	INSERT INTO session (
//	  user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, ip_address, user_agent
//	) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
//	RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessExp,
		arg.RefreshExp,
		arg.AccessJti,
		arg.RefreshJti,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const expireAccessTokenByJTI = `-- name: ExpireAccessTokenByJTI :one
UPDATE session
   SET access_status = 'expired', updated_at = timezone('utc', now())
WHERE access_jti = $1
RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

// ExpireAccessTokenByJTI
//
//	UPDATE session
//	   SET access_status = 'expired', updated_at = timezone('utc', now())
//	WHERE access_jti = $1
//	RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) ExpireAccessTokenByJTI(ctx context.Context, accessJti string) (*Session, error) {
	row := q.db.QueryRow(ctx, expireAccessTokenByJTI, accessJti)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at FROM session WHERE id = $1
`

// GetSessionByID
//
//	SELECT id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at FROM session WHERE id = $1
func (q *Queries) GetSessionByID(ctx context.Context, id string) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at FROM session WHERE user_id = $1 ORDER BY created_at DESC
`

// ListSessionsByUserID
//
//	SELECT id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at FROM session WHERE user_id = $1 ORDER BY created_at DESC
func (q *Queries) ListSessionsByUserID(ctx context.Context, userID string) ([]*Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessExp,
			&i.RefreshExp,
			&i.AccessJti,
			&i.RefreshJti,
			&i.AccessStatus,
			&i.RefreshStatus,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessTokenByJTI = `-- name: RevokeAccessTokenByJTI :one
UPDATE session
   SET access_status = 'revoked', updated_at = timezone('utc', now())
 WHERE access_jti = $1 RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

// RevokeAccessTokenByJTI
//
//	UPDATE session
//	   SET access_status = 'revoked', updated_at = timezone('utc', now())
//	 WHERE access_jti = $1 RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) RevokeAccessTokenByJTI(ctx context.Context, accessJti string) (*Session, error) {
	row := q.db.QueryRow(ctx, revokeAccessTokenByJTI, accessJti)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const rotateTokensByID = `-- name: RotateTokensByID :one
UPDATE session
SET access_token = $2, access_jti = $3, access_exp = $4,
    refresh_token = $5, refresh_jti = $6, refresh_exp = $7,
    updated_at = timezone('utc', now())
WHERE id = $1
RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

type RotateTokensByIDParams struct {
	ID           string           `json:"id"`
	AccessToken  string           `json:"access_token"`
	AccessJti    string           `json:"access_jti"`
	AccessExp    pgtype.Timestamp `json:"access_exp"`
	RefreshToken string           `json:"refresh_token"`
	RefreshJti   string           `json:"refresh_jti"`
	RefreshExp   pgtype.Timestamp `json:"refresh_exp"`
}

// RotateTokensByID
//
//	UPDATE session
//	SET access_token = $2, access_jti = $3, access_exp = $4,
//	    refresh_token = $5, refresh_jti = $6, refresh_exp = $7,
//	    updated_at = timezone('utc', now())
//	WHERE id = $1
//	RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) RotateTokensByID(ctx context.Context, arg *RotateTokensByIDParams) (*Session, error) {
	row := q.db.QueryRow(ctx, rotateTokensByID,
		arg.ID,
		arg.AccessToken,
		arg.AccessJti,
		arg.AccessExp,
		arg.RefreshToken,
		arg.RefreshJti,
		arg.RefreshExp,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateAccessTokenByID = `-- name: UpdateAccessTokenByID :one
UPDATE session
   SET access_token = $2, access_jti = $3, access_exp = $4
 WHERE id = $1 RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

type UpdateAccessTokenByIDParams struct {
	ID          string           `json:"id"`
	AccessToken string           `json:"access_token"`
	AccessJti   string           `json:"access_jti"`
	AccessExp   pgtype.Timestamp `json:"access_exp"`
}

// UpdateAccessTokenByID
//
//	UPDATE session
//	   SET access_token = $2, access_jti = $3, access_exp = $4
//	 WHERE id = $1 RETURNING id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_jti, refresh_jti, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) UpdateAccessTokenByID(ctx context.Context, arg *UpdateAccessTokenByIDParams) (*Session, error) {
	row := q.db.QueryRow(ctx, updateAccessTokenByID,
		arg.ID,
		arg.AccessToken,
		arg.AccessJti,
		arg.AccessExp,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessJti,
		&i.RefreshJti,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
