// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: session.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSessions = `-- name: CountSessions :one
select count(*) from session
`

// CountSessions
//
//	select count(*) from session
func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
insert into session (
    user_id,
    access_token,
    refresh_token,
    access_exp,
    refresh_exp,
    ip_address,
    user_agent
) values (
    $1, $2, $3, $4, $5, $6, $7
)
returning
    id, user_id, access_token, refresh_token, access_exp, refresh_exp,
    access_status, refresh_status, ip_address, user_agent, created_at, updated_at
`

type CreateSessionParams struct {
	UserID       string           `json:"user_id"`
	AccessToken  string           `json:"access_token"`
	RefreshToken string           `json:"refresh_token"`
	AccessExp    pgtype.Timestamp `json:"access_exp"`
	RefreshExp   pgtype.Timestamp `json:"refresh_exp"`
	IpAddress    string           `json:"ip_address"`
	UserAgent    string           `json:"user_agent"`
}

// CreateSession
//
//	insert into session (
//	    user_id,
//	    access_token,
//	    refresh_token,
//	    access_exp,
//	    refresh_exp,
//	    ip_address,
//	    user_agent
//	) values (
//	    $1, $2, $3, $4, $5, $6, $7
//	)
//	returning
//	    id, user_id, access_token, refresh_token, access_exp, refresh_exp,
//	    access_status, refresh_status, ip_address, user_agent, created_at, updated_at
func (q *Queries) CreateSession(ctx context.Context, arg *CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessExp,
		arg.RefreshExp,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const expireAccessTokenByID = `-- name: ExpireAccessTokenByID :one
update session
set access_status = 'expired'
where id = $1
returning id, access_status
`

type ExpireAccessTokenByIDRow struct {
	ID           string `json:"id"`
	AccessStatus string `json:"access_status"`
}

// ExpireAccessTokenByID
//
//	update session
//	set access_status = 'expired'
//	where id = $1
//	returning id, access_status
func (q *Queries) ExpireAccessTokenByID(ctx context.Context, id string) (*ExpireAccessTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, expireAccessTokenByID, id)
	var i ExpireAccessTokenByIDRow
	err := row.Scan(&i.ID, &i.AccessStatus)
	return &i, err
}

const expireRefreshTokenByID = `-- name: ExpireRefreshTokenByID :one
update session
set refresh_status = 'expired'
where id = $1
returning id, refresh_status
`

type ExpireRefreshTokenByIDRow struct {
	ID            string `json:"id"`
	RefreshStatus string `json:"refresh_status"`
}

// ExpireRefreshTokenByID
//
//	update session
//	set refresh_status = 'expired'
//	where id = $1
//	returning id, refresh_status
func (q *Queries) ExpireRefreshTokenByID(ctx context.Context, id string) (*ExpireRefreshTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, expireRefreshTokenByID, id)
	var i ExpireRefreshTokenByIDRow
	err := row.Scan(&i.ID, &i.RefreshStatus)
	return &i, err
}

const getSessionByAccessToken = `-- name: GetSessionByAccessToken :one
select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
from session
where access_token = $1
  and access_status = 'valid'
`

// GetSessionByAccessToken
//
//	select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
//	from session
//	where access_token = $1
//	  and access_status = 'valid'
func (q *Queries) GetSessionByAccessToken(ctx context.Context, accessToken string) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByAccessToken, accessToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionByID = `-- name: GetSessionByID :one
select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
from session
where id = $1
`

// GetSessionByID
//
//	select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
//	from session
//	where id = $1
func (q *Queries) GetSessionByID(ctx context.Context, id string) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
from session
where refresh_token = $1
  and refresh_status = 'valid'
`

// GetSessionByRefreshToken
//
//	select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
//	from session
//	where refresh_token = $1
//	  and refresh_status = 'valid'
func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.AccessExp,
		&i.RefreshExp,
		&i.AccessStatus,
		&i.RefreshStatus,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
from session
where user_id = $1
order by created_at desc
`

// ListSessionsByUserID
//
//	select id, user_id, access_token, refresh_token, access_exp, refresh_exp, access_status, refresh_status, ip_address, user_agent, created_at, updated_at
//	from session
//	where user_id = $1
//	order by created_at desc
func (q *Queries) ListSessionsByUserID(ctx context.Context, userID string) ([]*Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.AccessExp,
			&i.RefreshExp,
			&i.AccessStatus,
			&i.RefreshStatus,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessTokenByID = `-- name: RevokeAccessTokenByID :one
update session
set access_status = 'revoked'
where id = $1
returning id, user_id, access_status
`

type RevokeAccessTokenByIDRow struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	AccessStatus string `json:"access_status"`
}

// RevokeAccessTokenByID
//
//	update session
//	set access_status = 'revoked'
//	where id = $1
//	returning id, user_id, access_status
func (q *Queries) RevokeAccessTokenByID(ctx context.Context, id string) (*RevokeAccessTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, revokeAccessTokenByID, id)
	var i RevokeAccessTokenByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.AccessStatus)
	return &i, err
}

const revokeRefreshTokenByID = `-- name: RevokeRefreshTokenByID :one
update session
set refresh_status = 'revoked'
where id = $1
returning id, user_id, refresh_status
`

type RevokeRefreshTokenByIDRow struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	RefreshStatus string `json:"refresh_status"`
}

// RevokeRefreshTokenByID
//
//	update session
//	set refresh_status = 'revoked'
//	where id = $1
//	returning id, user_id, refresh_status
func (q *Queries) RevokeRefreshTokenByID(ctx context.Context, id string) (*RevokeRefreshTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, revokeRefreshTokenByID, id)
	var i RevokeRefreshTokenByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.RefreshStatus)
	return &i, err
}

const updateAccessTokenByID = `-- name: UpdateAccessTokenByID :one
update session
set access_token = $1,
    access_exp = $2,
    access_status = 'valid'
where id = $3
returning id, access_token, access_exp, access_status
`

type UpdateAccessTokenByIDParams struct {
	AccessToken string           `json:"access_token"`
	AccessExp   pgtype.Timestamp `json:"access_exp"`
	ID          string           `json:"id"`
}

type UpdateAccessTokenByIDRow struct {
	ID           string           `json:"id"`
	AccessToken  string           `json:"access_token"`
	AccessExp    pgtype.Timestamp `json:"access_exp"`
	AccessStatus string           `json:"access_status"`
}

// UpdateAccessTokenByID
//
//	update session
//	set access_token = $1,
//	    access_exp = $2,
//	    access_status = 'valid'
//	where id = $3
//	returning id, access_token, access_exp, access_status
func (q *Queries) UpdateAccessTokenByID(ctx context.Context, arg *UpdateAccessTokenByIDParams) (*UpdateAccessTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, updateAccessTokenByID, arg.AccessToken, arg.AccessExp, arg.ID)
	var i UpdateAccessTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.AccessExp,
		&i.AccessStatus,
	)
	return &i, err
}

const updateRefreshTokenByID = `-- name: UpdateRefreshTokenByID :one
update session
set refresh_token = $1,
    refresh_exp = $2,
    refresh_status = 'valid'
where id = $3
returning id, refresh_token, refresh_exp, refresh_status
`

type UpdateRefreshTokenByIDParams struct {
	RefreshToken string           `json:"refresh_token"`
	RefreshExp   pgtype.Timestamp `json:"refresh_exp"`
	ID           string           `json:"id"`
}

type UpdateRefreshTokenByIDRow struct {
	ID            string           `json:"id"`
	RefreshToken  string           `json:"refresh_token"`
	RefreshExp    pgtype.Timestamp `json:"refresh_exp"`
	RefreshStatus string           `json:"refresh_status"`
}

// UpdateRefreshTokenByID
//
//	update session
//	set refresh_token = $1,
//	    refresh_exp = $2,
//	    refresh_status = 'valid'
//	where id = $3
//	returning id, refresh_token, refresh_exp, refresh_status
func (q *Queries) UpdateRefreshTokenByID(ctx context.Context, arg *UpdateRefreshTokenByIDParams) (*UpdateRefreshTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, updateRefreshTokenByID, arg.RefreshToken, arg.RefreshExp, arg.ID)
	var i UpdateRefreshTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.RefreshToken,
		&i.RefreshExp,
		&i.RefreshStatus,
	)
	return &i, err
}
