// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users_queries.sql

package dbs

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password, is_checked)
VALUES ($1, $2, $3) RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
`

type CreateUserParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	IsChecked bool   `json:"is_checked"`
}

// CreateUser
//
//	INSERT INTO users (username, password, is_checked)
//	VALUES ($1, $2, $3) RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Password, arg.IsChecked)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUserByID = `-- name: DeleteUserByID :one
DELETE FROM users WHERE id = $1 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
`

// DeleteUserByID
//
//	DELETE FROM users WHERE id = $1 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
func (q *Queries) DeleteUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, deleteUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users WHERE id = $1
`

// GetUserByID
//
//	SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users WHERE id = $1
func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users WHERE username = $1
`

// GetUserByUsername
//
//	SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users WHERE username = $1
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users ORDER BY created_at DESC
`

// ListUsers
//
//	SELECT id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at FROM users ORDER BY created_at DESC
func (q *Queries) ListUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.IsBlocked,
			&i.BlockedAt,
			&i.IsChecked,
			&i.CheckedAt,
			&i.VisitedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE users
   SET username = $1, password = $2, is_checked = $3, is_blocked = $4
 WHERE id = $5 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
`

type UpdateUserByIDParams struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	IsChecked bool   `json:"is_checked"`
	IsBlocked bool   `json:"is_blocked"`
	ID        string `json:"id"`
}

// UpdateUserByID
//
//	UPDATE users
//	   SET username = $1, password = $2, is_checked = $3, is_blocked = $4
//	 WHERE id = $5 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
func (q *Queries) UpdateUserByID(ctx context.Context, arg *UpdateUserByIDParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserByID,
		arg.Username,
		arg.Password,
		arg.IsChecked,
		arg.IsBlocked,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserIsBlockedByID = `-- name: UpdateUserIsBlockedByID :one
UPDATE users
   SET is_blocked = $1,
       blocked_at = CASE WHEN $1 THEN NOW() ELSE '1000-01-01'::timestamp END,
       updated_at = NOW()
 WHERE id = $2 RETURNING id, username, is_blocked, is_checked
`

type UpdateUserIsBlockedByIDParams struct {
	IsBlocked bool   `json:"is_blocked"`
	ID        string `json:"id"`
}

type UpdateUserIsBlockedByIDRow struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	IsBlocked bool   `json:"is_blocked"`
	IsChecked bool   `json:"is_checked"`
}

// UpdateUserIsBlockedByID
//
//	UPDATE users
//	   SET is_blocked = $1,
//	       blocked_at = CASE WHEN $1 THEN NOW() ELSE '1000-01-01'::timestamp END,
//	       updated_at = NOW()
//	 WHERE id = $2 RETURNING id, username, is_blocked, is_checked
func (q *Queries) UpdateUserIsBlockedByID(ctx context.Context, arg *UpdateUserIsBlockedByIDParams) (*UpdateUserIsBlockedByIDRow, error) {
	row := q.db.QueryRow(ctx, updateUserIsBlockedByID, arg.IsBlocked, arg.ID)
	var i UpdateUserIsBlockedByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.IsBlocked,
		&i.IsChecked,
	)
	return &i, err
}

const updateVisitedAtByUserID = `-- name: UpdateVisitedAtByUserID :one
UPDATE users SET visited_at = $1 WHERE id = $2 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
`

type UpdateVisitedAtByUserIDParams struct {
	VisitedAt pgtype.Timestamp `json:"visited_at"`
	ID        string           `json:"id"`
}

// UpdateVisitedAtByUserID
//
//	UPDATE users SET visited_at = $1 WHERE id = $2 RETURNING id, username, password, is_blocked, blocked_at, is_checked, checked_at, visited_at, created_at, updated_at
func (q *Queries) UpdateVisitedAtByUserID(ctx context.Context, arg *UpdateVisitedAtByUserIDParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateVisitedAtByUserID, arg.VisitedAt, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.IsBlocked,
		&i.BlockedAt,
		&i.IsChecked,
		&i.CheckedAt,
		&i.VisitedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
