// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_roles.sql

package dbs

import (
	"context"
)

const createUserRole = `-- name: CreateUserRole :one

INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
RETURNING id, user_id, role_id, created_at
`

type CreateUserRoleParams struct {
	UserID string `json:"user_id"`
	RoleID string `json:"role_id"`
}

// UserRoles
// Create
//
//	INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)
//	RETURNING id, user_id, role_id, created_at
func (q *Queries) CreateUserRole(ctx context.Context, arg *CreateUserRoleParams) (*UserRole, error) {
	row := q.db.QueryRow(ctx, createUserRole, arg.UserID, arg.RoleID)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteUserRoleByID = `-- name: DeleteUserRoleByID :one
DELETE FROM user_roles WHERE id = $1
RETURNING id, user_id, role_id, created_at
`

// Delete
//
//	DELETE FROM user_roles WHERE id = $1
//	RETURNING id, user_id, role_id, created_at
func (q *Queries) DeleteUserRoleByID(ctx context.Context, id string) (*UserRole, error) {
	row := q.db.QueryRow(ctx, deleteUserRoleByID, id)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
	)
	return &i, err
}

const getUserRoleByID = `-- name: GetUserRoleByID :one
SELECT id, user_id, role_id, created_at FROM user_roles WHERE id = $1
`

// Get by ID
//
//	SELECT id, user_id, role_id, created_at FROM user_roles WHERE id = $1
func (q *Queries) GetUserRoleByID(ctx context.Context, id string) (*UserRole, error) {
	row := q.db.QueryRow(ctx, getUserRoleByID, id)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.CreatedAt,
	)
	return &i, err
}

const listUserRolesByRoleID = `-- name: ListUserRolesByRoleID :many
SELECT id, user_id, role_id, created_at FROM user_roles WHERE role_id = $1
`

// List by RoleID
//
//	SELECT id, user_id, role_id, created_at FROM user_roles WHERE role_id = $1
func (q *Queries) ListUserRolesByRoleID(ctx context.Context, roleID string) ([]*UserRole, error) {
	rows, err := q.db.Query(ctx, listUserRolesByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRolesByUserID = `-- name: ListUserRolesByUserID :many
SELECT id, user_id, role_id, created_at FROM user_roles WHERE user_id = $1
`

// List by UserID
//
//	SELECT id, user_id, role_id, created_at FROM user_roles WHERE user_id = $1
func (q *Queries) ListUserRolesByUserID(ctx context.Context, userID string) ([]*UserRole, error) {
	rows, err := q.db.Query(ctx, listUserRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserRole
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
