@baseUrl = http://localhost:8081/api/v1/auth
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkNGNwcmpxOGhtcmxpaWhyNjZvZyIsImp0aSI6ImQ0Y3RxaXE1bWpqMmhxOWZycnIwIiwic2lkIjoiZDRjdHFhaThobXJqMjA5cjY2czAiLCJleHAiOjE3NjMzMDM2MzEsImlhdCI6MTc2MzMwMjczMX0.3dzh-uOOE5diuDHgr1FFr4tXbE0ubQCLVDaX4rxVgSY
@refreshToken = 084b0e18cb3c21770b908e798a662f58e9a958912125d5549e4a5549a19033ef
@userID = d4cprjq8hmrliihr66og
@sessionID = d4cto7i8hmrj209r66rg

### -------------------------------
### 1. Register a new user
POST {{baseUrl}}/register
Content-Type: application/json

{
  "username": "user15",
  "password": "passw0rd"
}

###

### -------------------------------
### 2. Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "user15",
  "password": "passw0rd"
}

###

### -------------------------------
### 3. Get current user info (Me)
GET {{baseUrl}}/me
Authorization: Bearer {{accessToken}}

###

### -------------------------------
### 4. Refresh access token
POST {{baseUrl}}/refresh
Content-Type: application/json

{
  "user_id": "{{userID}}",
  "refresh_token": "{{refreshToken}}"
}

###

### -------------------------------
### 5. Logout
POST {{baseUrl}}/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "session_id": "{{sessionID}}"
}

###

### -------------------------------
### 6. Block user
POST {{baseUrl}}/block/{{userID}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "blocked": true
}

###

### -------------------------------
### 7. Unblock user
POST {{baseUrl}}/block/{{userID}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "blocked": false
}
