// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: roles.sql

package dbs

import (
	"context"
)

const rolesCount = `-- name: RolesCount :one
select count(*) from roles
`

// RolesCount
//
//	select count(*) from roles
func (q *Queries) RolesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, rolesCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const rolesDeleteByID = `-- name: RolesDeleteByID :one
delete from roles where id = $1 returning id
`

// RolesDeleteByID
//
//	delete from roles where id = $1 returning id
func (q *Queries) RolesDeleteByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, rolesDeleteByID, id)
	err := row.Scan(&id)
	return id, err
}

const rolesNew = `-- name: RolesNew :one
insert into roles(name) values($1) returning id, name, created_at, updated_at
`

// RolesNew
//
//	insert into roles(name) values($1) returning id, name, created_at, updated_at
func (q *Queries) RolesNew(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, rolesNew, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const rolesSelect = `-- name: RolesSelect :many
select id, name, created_at, updated_at
  from roles r
 order by $1::text
 limit $3 offset $2
`

type RolesSelectParams struct {
	SqlOrder  string `json:"sql_order"`
	SqlOffset int32  `json:"sql_offset"`
	SqlLimit  int32  `json:"sql_limit"`
}

// RolesSelect
//
//	select id, name, created_at, updated_at
//	  from roles r
//	 order by $1::text
//	 limit $3 offset $2
func (q *Queries) RolesSelect(ctx context.Context, arg *RolesSelectParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, rolesSelect, arg.SqlOrder, arg.SqlOffset, arg.SqlLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rolesSelectByID = `-- name: RolesSelectByID :one
select id, name, created_at, updated_at from roles r where r.id = $1
`

// RolesSelectByID
//
//	select id, name, created_at, updated_at from roles r where r.id = $1
func (q *Queries) RolesSelectByID(ctx context.Context, id string) (*Role, error) {
	row := q.db.QueryRow(ctx, rolesSelectByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const rolesSelectByName = `-- name: RolesSelectByName :one
select id, name, created_at, updated_at from roles r where r.name = $1
`

// RolesSelectByName
//
//	select id, name, created_at, updated_at from roles r where r.name = $1
func (q *Queries) RolesSelectByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, rolesSelectByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const rolesUpdateByID = `-- name: RolesUpdateByID :one
update roles
   set name = $1 where id = $2 returning id, name, created_at, updated_at
`

type RolesUpdateByIDParams struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

// RolesUpdateByID
//
//	update roles
//	   set name = $1 where id = $2 returning id, name, created_at, updated_at
func (q *Queries) RolesUpdateByID(ctx context.Context, arg *RolesUpdateByIDParams) (*Role, error) {
	row := q.db.QueryRow(ctx, rolesUpdateByID, arg.Name, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
